[package]
name = "math_cat_demo"
version = "0.1.0"
edition = "2018"


[dependencies]
yew = "0.18"
wasm-bindgen = "0.2"
lazy_static = "1.4.0"
regex = "1.5"

[dependencies.web-sys]
version = "0.3"
features = ["HtmlInputElement"]
