[serve]
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = true		# changed from default
# Disable auto-reload of the web app.
no_autoreload = false

[build]
public_url = "/MathCATDemo/"
